# Example PoliteChat Configuration

words:
  # English examples
  idiot: genius
  stupid: brilliant one
  noob: pro learner

  # Hindi examples
  bakwas: awesome
  gadha: smart one
  pagal: creative mind
