# NiceChat Configuration
# Add as many words as you want
# Format: "badword: niceword"

words:
  # English words: Nice words
  asshole: sunshine
  bastard: champion
  bitch: queen
  bimbo: genius
  bozo: superstar
  bugger: hero
  bullshit: nonsense
  cunt: angel
  dickhead: brainiac
  douchebag: innovator
  faggot: champion
  fucker: legend
  idiot: genius
  jerk: hero
  moron: superstar
  prick: innovator
  shit: nonsense
  twat: brainiac
  wanker: champion
  noob: pro learner man
  gay: superstar

  # Hindi / Indian words: Nice words
  chutiya: champ
  chakke: star 
  chakka: superstar 
  bhosdi: flower
  madarchod: legend
  gandu: hero
  kutte: sher
  bhosdike: big bro
  bsdk: big bro
  bc: sister's hero
  behenchod: big brother
  bhains ki aulad: bhaish bhi hamari mata hai?
  bhains ki aankh: buffalo is nice
  bhen ke laude: didi's buddy
  bhen ke takke: didi helper
  beti chod: you brave brother
  bhai chod: mitrata rakho
  jhalla: silly goose
  gaand: pen
  gaandu: smart
  lavda: buddy
  lavde: bhai
  lund: champ
  lavde ke bal: nice hair
  rundi: superstar
  rundi ka bacha: little hero
  rundi ki bachi: little champ
  soower ke bachhe: good guy
  ullu ke pathe: you are clever
  padma: bunny
  raand ka jamai: great son
  randhwa: funny guy
  jhaant ke pissu: tiny champ
  chut: cutie pie
  chodu: playful buddy
  chodra: mischievous one
  choochii: sweetheart
  mc: mother's hero
  muth mar: daydreamer
  muththal: bodybuilder
  nimbu sharbat: silly fellow
  teri maa ki chut: your mother is my mother 
  maa ke laude: loving one

