name: PoliteChat
main: com.knightgost.politechat.PoliteChat
version: 1.0.0
api-version: 1.20
author: KnightGost (virendraxd)
description: Replaces bad words with polite words — spread positivity!

commands:
  politechat:
    description: Manage PoliteChat plugin
    usage: /<command> <reload>
    permission: politechat.admin
    permission-message: You don't have permission to use this command!